# Generated by Django 4.1.6 on 2023-02-17 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reaL_name", models.CharField(max_length=200, null=True)),
                ("nick_name", models.CharField(max_length=100, null=True)),
                ("time", models.TimeField(null=True)),
                ("date", models.DateField(null=True)),
                ("story", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Counsellor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("contact", models.IntegerField(null=True)),
                ("text", models.TextField(null=True)),
                ("twitter", models.TextField(null=True)),
                ("instagram", models.TextField(null=True)),
                ("website", models.TextField(null=True)),
                ("reviews", models.IntegerField(null=True)),
                ("date", models.DateField(null=True)),
                ("story", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reply", models.TextField(null=True)),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="counsel.client",
                    ),
                ),
            ],
        ),
    ]
